package com.gymfit;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.transaction.annotation.Transactional;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;
import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1","gymfit.admin.password=TestPassword123!"})
@AutoConfigureMockMvc @Transactional class GymFitIntegrationTest {
 @Autowired MockMvc mvc; @Autowired ExerciseRepository exercises; @Autowired RoutineRepository routines; @Autowired LogRepository logs;
 @Test void anonymousIsRedirected()throws Exception{mvc.perform(get("/")).andExpect(status().is3xxRedirection()).andExpect(redirectedUrlPattern("**/login"));mvc.perform(get("/login")).andExpect(status().isOk());}
 @Test void credentialsWork()throws Exception{mvc.perform(post("/login").with(csrf()).param("username","admin").param("password","TestPassword123!")).andExpect(status().is3xxRedirection()).andExpect(redirectedUrl("/"));}
 @Test @WithMockUser(roles="ADMIN") void pagesRender()throws Exception{for(String path:new String[]{"/","/exercises","/exercises/new","/routines","/routines/new","/history"})mvc.perform(get(path)).andExpect(status().isOk());Long id=routines.findAll().get(0).id;mvc.perform(get("/routines/"+id)).andExpect(status().isOk());mvc.perform(get("/routines/"+id+"/edit")).andExpect(status().isOk());mvc.perform(get("/exercises/"+exercises.findAll().get(0).id+"/edit")).andExpect(status().isOk());}
 @Test @WithMockUser(roles="ADMIN") void csrfAndValidation()throws Exception{mvc.perform(post("/exercises/save")).andExpect(status().isForbidden());mvc.perform(post("/exercises/save").with(csrf()).param("name","").param("muscle","Core").param("difficulty","Principiante").param("equipment","Colchoneta").param("description","Texto")).andExpect(status().isBadRequest());}
 @Test @WithMockUser(roles="ADMIN") void routineLifecyclePreservesHistory()throws Exception{Long e=exercises.findAll().get(0).id;long n=routines.count();mvc.perform(post("/routines/save").with(csrf()).param("name","Rutina prueba").param("goal","Fuerza").param("day","Lunes").param("difficulty","Intermedio").param("exerciseId",e.toString()).param("sets","3").param("reps","10").param("rest","60")).andExpect(status().is3xxRedirection());assertEquals(n+1,routines.count());Routine r=routines.findAll().stream().filter(x->x.name.equals("Rutina prueba")).findFirst().orElseThrow();mvc.perform(post("/routines/"+r.id+"/log").with(csrf()).param("date",java.time.LocalDate.now().toString()).param("minutes","45").param("notes","Primera sesión")).andExpect(status().is3xxRedirection());assertEquals(1,logs.count());mvc.perform(post("/routines/save").with(csrf()).param("id",r.id.toString()).param("name","Rutina editada").param("goal","Fuerza").param("day","Martes").param("difficulty","Intermedio").param("exerciseId",e.toString()).param("sets","4").param("reps","12").param("rest","90")).andExpect(status().is3xxRedirection());mvc.perform(post("/routines/"+r.id+"/delete").with(csrf())).andExpect(status().is3xxRedirection());assertEquals(n,routines.count());assertEquals("Rutina prueba",logs.findAll().get(0).routineName);}
 @Test @WithMockUser(roles="ADMIN") void usedExerciseCannotBeDeleted()throws Exception{Long id=routines.findAll().get(0).items.get(0).exercise.id;mvc.perform(post("/exercises/"+id+"/delete").with(csrf())).andExpect(flash().attributeExists("error"));assertTrue(exercises.existsById(id));}
 @Test @WithMockUser(roles="USER") void otherRolesForbidden()throws Exception{mvc.perform(get("/exercises")).andExpect(status().isForbidden());}
 @Test @WithMockUser(roles="ADMIN") void exerciseCrudAndFutureSessionValidation()throws Exception{long count=exercises.count();mvc.perform(post("/exercises/save").with(csrf()).param("name","Ejercicio de prueba").param("muscle","Core").param("difficulty","Principiante").param("equipment","Colchoneta").param("description","Prueba de descripción")).andExpect(status().is3xxRedirection());assertEquals(count+1,exercises.count());Exercise e=exercises.findAll().stream().filter(x->x.name.equals("Ejercicio de prueba")).findFirst().orElseThrow();mvc.perform(post("/exercises/save").with(csrf()).param("id",e.id.toString()).param("name","Ejercicio editado").param("muscle","Core").param("difficulty","Intermedio").param("equipment","Colchoneta").param("description","Descripción editada")).andExpect(status().is3xxRedirection());assertEquals("Ejercicio editado",exercises.findById(e.id).orElseThrow().name);mvc.perform(post("/exercises/"+e.id+"/delete").with(csrf())).andExpect(status().is3xxRedirection());assertEquals(count,exercises.count());Long r=routines.findAll().get(0).id;mvc.perform(post("/routines/"+r+"/log").with(csrf()).param("date",java.time.LocalDate.now().plusDays(1).toString()).param("minutes","45")).andExpect(status().isBadRequest());assertEquals(0,logs.count());}
}
